[tool.poetry]
name = "pydris"
version = "0.1.0"
description = "A simple pythonic API wrapper for Eludris"
authors = ["Enoki <enokiun@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
